[package]
name = "client-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
rmp-serde = "1.3.0"
tokio = { version = "1.44.0", features = ["full"] }
config = "0.15.11"
protocol = { path = "../protocol" }

