[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
rmp-serde = "1.3.0"

[features]
with_msgpack = []
with_pvaccess = []
default = ["with_msgpack"]
