
[workspace]
resolver = "2"
members = [
    "crates/client",
    "crates/client-lib",
    "crates/protocol",
    "crates/msg-server",
    "crates/pv-server",

    "examples/hello",
    "examples/multi_client",
    "tests",
]
