name: Run Integration Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Server
        run: cargo build --bin server

      - name: Start Server in Background
        run: cargo run --bin server &

      - name: Wait for Server to Start
        run: sleep 2  # Give it time to initialize

      - name: Run Integration Tests
        run: cargo test --test create_channel --test validate_schema --test metadata_request
